In [4]:
import numpy as np
import pandas as pd

In [39]:
df.head(2)

Make       Model  Year             Engine Fuel Type  Engine HP  \
0  BMW  1 Series M  2011  premium unleaded (required)      335.0   
1  BMW    1 Series  2011  premium unleaded (required)      300.0   

   Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
0               6.0            MANUAL  rear wheel drive              2.0   
1               6.0            MANUAL  rear wheel drive              2.0   

                         Market Category Vehicle Size Vehicle Style  \
0  Factory Tuner,Luxury,High-Performance      Compact         Coupe   
1                     Luxury,Performance      Compact   Convertible   

   highway MPG  city mpg  Popularity   MSRP  
0           26        19        3916  46135  
1           28        19        3916  40650

#### 1) The version installed is 1.23.2

In [3]:
#
np.__version__ 

'1.23.2'

In [6]:
df=pd.read_csv('Homework1.csv')

#### 2)The file has 11914 rows.

In [8]:
df.shape

(11914, 16)

#### 3)The most frequent car manufacturers are Chevrolet, Ford, Volkswagen

In [75]:
df.groupby('Make')['Make'].count().sort_values(ascending=False)

Make
Chevrolet        1123
Ford              881
Volkswagen        809
Toyota            746
Dodge             626
Nissan            558
GMC               515
Honda             449
Mazda             423
Cadillac          397
Mercedes-Benz     353
Suzuki            351
BMW               334
Infiniti          330
Audi              328
Hyundai           303
Volvo             281
Subaru            256
Acura             252
Kia               231
Mitsubishi        213
Lexus             202
Buick             196
Chrysler          187
Pontiac           186
Lincoln           164
Oldsmobile        150
Land Rover        143
Porsche           136
Saab              111
Aston Martin       93
Plymouth           82
Bentley            74
Ferrari            69
FIAT               62
Scion              60
Maserati           58
Lamborghini        52
Rolls-Royce        31
Lotus              29
Tesla              18
HUMMER             17
Maybach            16
McLaren             5
Alfa Romeo          5
Spyke

#### 4)There are 34 unique Audi car models in the dataset

In [50]:
df[
    df['Make']=='Audi'
].Model.nunique()

34

#### 5)There are 5 columns with missing values

In [54]:
df.isnull().sum()

Make                    0
Model                   0
Year                    0
Engine Fuel Type        3
Engine HP              69
Engine Cylinders       30
Transmission Type       0
Driven_Wheels           0
Number of Doors         6
Market Category      3742
Vehicle Size            0
Vehicle Style           0
highway MPG             0
city mpg                0
Popularity              0
MSRP                    0
dtype: int64

#### 6)The median value is almost the same 5.62 so there is no big changes after replacing missing values

In [57]:
df['Engine Cylinders'].mean() #Median Value= 5.6288

5.628828677213059

In [74]:
df.groupby('Engine Cylinders')['Engine Cylinders'].count().sort_values(ascending=False) # Most frequent Value = 4.0

Engine Cylinders
4.0     4752
6.0     4489
8.0     2031
12.0     230
5.0      225
10.0      68
0.0       56
3.0       30
16.0       3
Name: Engine Cylinders, dtype: int64

In [76]:
df['Engine Cylinders'] = df['Engine Cylinders'].fillna(4.0) #Replace null with 4.0

In [77]:
df.isnull().sum()

Make                    0
Model                   0
Year                    0
Engine Fuel Type        3
Engine HP              69
Engine Cylinders        0
Transmission Type       0
Driven_Wheels           0
Number of Doors         6
Market Category      3742
Vehicle Size            0
Vehicle Style           0
highway MPG             0
city mpg                0
Popularity              0
MSRP                    0
dtype: int64

In [78]:
df['Engine Cylinders'].mean() # The mean is almost the same 5.62

5.624727211683734

In [79]:
df.head(2)

Make       Model  Year             Engine Fuel Type  Engine HP  \
0  BMW  1 Series M  2011  premium unleaded (required)      335.0   
1  BMW    1 Series  2011  premium unleaded (required)      300.0   

   Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
0               6.0            MANUAL  rear wheel drive              2.0   
1               6.0            MANUAL  rear wheel drive              2.0   

                         Market Category Vehicle Size Vehicle Style  \
0  Factory Tuner,Luxury,High-Performance      Compact         Coupe   
1                     Luxury,Performance      Compact   Convertible   

   highway MPG  city mpg  Popularity   MSRP  
0           26        19        3916  46135  
1           28        19        3916  40650

#### 7)The value of W is 4.5949

In [94]:
df[df['Make']=='Lotus'][["Engine HP","Engine Cylinders"]].drop_duplicates()

Engine HP  Engine Cylinders
3912      189.0               4.0
3913      218.0               4.0
3918      217.0               4.0
4216      350.0               8.0
4257      400.0               6.0
4259      276.0               6.0
4262      345.0               6.0
4292      257.0               4.0
4293      240.0               4.0

In [95]:
X=df[df['Make']=='Lotus'][["Engine HP","Engine Cylinders"]].drop_duplicates().values

In [104]:
X

array([[189.,   4.],
       [218.,   4.],
       [217.,   4.],
       [350.,   8.],
       [400.,   6.],
       [276.,   6.],
       [345.,   6.],
       [257.,   4.],
       [240.,   4.]])

In [123]:
XTX=np.dot(X.T,X)

In [126]:
XTX

array([[7.31684e+05, 1.34100e+04],
       [1.34100e+04, 2.52000e+02]])

In [130]:
Z=np.linalg.inv(XTX)

In [131]:
Z

array([[ 5.53084235e-05, -2.94319825e-03],
       [-2.94319825e-03,  1.60588447e-01]])

In [128]:
y=np.array([1100, 800, 750, 850, 1300, 1000, 1000, 1300, 800])

In [129]:
y

array([1100,  800,  750,  850, 1300, 1000, 1000, 1300,  800])

In [133]:
L=np.dot(Z,X.T)

In [136]:
np.dot(L,y) #Result 4,59

array([  4.59494481, -63.56432501])